services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env
    working_dir: /superviso
    volumes:
      - ./templates:/superviso/templates
      - ./static:/superviso/static
    command: ["/wait-for-it.sh", "db:5432", "-t", "30", "--", "/superviso/app_superviso"]
    networks:
      - superviso_network

  db:
    image: postgres:16.4
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/migrations:/docker-entrypoint-initdb.d
    networks:
      - superviso_network

  backup:
    image: postgres:16.4
    volumes:
      - ./backups:/backups
      - ./scripts:/scripts
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    entrypoint: [""]
    command: ["/bin/bash", "-c", "while true; do /scripts/backup.sh; sleep 86400; done"]
    depends_on:
      - db
    networks:
      - superviso_network

networks:
  superviso_network:

volumes:
  db_data:
